#!/bin/bash

if [ "$#" -eq 3 ]; then
    a1=$2
    a2=$3
else
    a1=$1
    a2=$2
fi


base_dir=/Users/Phillip/Documents/Research/Resources/Notes/terminal_notes/links

# construct link filename (convention is to name link by writing linked note names in alphabetic order) 
LINK="_LINK_"
if [ "$a1" '<' "$a2" ]; then
    f="$a1$LINK$a2"
else
    f="$a2$LINK$a1"
fi


while getopts ":ec" opt; do

    case $opt in
	e)
	    emacs $base_dir/$f
	    exit
	    ;;
	c)
	    emacs $base_dir/$f
	    exit
	   ;;
	\?)
	    echo "Invalid option: -$OPTARG >&2"
	    exit
	    ;;
    esac
done

# if no option specified, just print out the link text
less $base_dir/$f